### ISSUE TITLE
`--add-to-all-source-repos` flag

### ISSUE THREAD

**Issue by sindresorhus** [kevva/github-add-collab#3]
Pretty much the same as `--add-to-all` but doesn't include forks. The flag will need a better name.

It's annoying for users to be added to a lot of useless forks. I used to have a lot until I cleaned them up recently.

**Comment by kevva** [comment]
Yup, I was thinking about this yesterday and decided to work on `github-remove-forks` to clean 'em up. Will add this flag though.

**Comment by sindresorhus** [comment]
Nice, I was going to ask you to make that, lol :D

**Comment by arthurvr** [comment]
> Nice, I was going to ask you to make that, lol :D

He already did :D https://github.com/kevva/github-remove-forks

**Comment by sindresorhus** [comment]
I know, that's why I commented.
