### ISSUE TITLE
Speed up and reduce rate limit use

### ISSUE THREAD

**Issue by sindresorhus** [kevva/github-add-collab#5]
Currently when I want to update eg. you to my latest repos it will try to add you to all of my repos again. This is slow on my connection, which is not the fastest, and it can easily use up my rate limit.

Would be nice if this module could somehow make use of https://developer.github.com/v3/#conditional-requests

**Comment by kevva** [comment]
@sindresorhus, could you try it out? Doesn't seem to work for me at least.

**Comment by sindresorhus** [comment]
Would be a lot easier to test if you had tests using test accounts. Hint hint ;)

Will try it out later.

**Comment by arthurvr** [comment]
Haha https://github.com/unicornbot

**Comment by kevva** [comment]
Sick dude.
